### ISSUE TITLE
Non-active tiles can't be activated manually

### ISSUE THREAD

**Issue by asl97** [cwmonkey/reactor-knockoff#19]
Non-active tiles can't be activated manually, resulting in players ether waiting or forced to remove and place again.

the players should be able to manually activate the tiles or the tiles should all get activated when there is enough money instead of just one per tick.

**Comment by cwmonkey** [comment]
@asl97 Haven't used github much, is there a way to grab your fixes into this repo?

**Comment by asl97** [comment]
@cwmonkey If you mean merging specific commit through github, as far as I am aware of, there isn't any.

If you use git, you can try the cherry-pick command, however I do doubt if it can cleanly merge some of the commit due to the numerous performance changes I did.

In fact, when I tried to cherry-pick the black hole accelerator fix, I still need to manually fix it up.

----
If you want to work off the top of my fork, it would be fairly simple from git, not from github though, 
```bash
git remote add asl97 https://github.com/asl97/reactor-knockoff
git checkout asl97/master -b name_of_new_branch
git push -u origin HEAD # assuming origin is your repo name
```
then from github update the default branch to the new branch.

or you can force override the current master branch with the new branch.
```bash
git push -f -u origin HEAD:master # dangerous, only use if you understand
```


----
I did not exactly created my fork with merging part of it back upstream in mind since there was a number of unmerged pull request which at that time was two years old.

**Comment by cwmonkey** [comment]
@asl97 Yeah I dropped the ball on that, sorry 😬 

I'll give syncing them up a shot.

**Comment by cwmonkey** [comment]
@asl97 ok, updated master to your master. Thanks for the help.

If you're cool with it you can send me PR's and I'll get them in asap.

Also feel free to give them some credit in game.
