### ISSUE TITLE
Bug in EP accounting?

### ISSUE THREAD

**Issue by egon010** [cwmonkey/reactor-knockoff#2]
I'm not sure how it's supposed to work, so I'm not 100% sure it's a bug, but I got a reactor into the Qa money range, and was able to build 32 1T particle accelerators, and keep them stable at 100% power. They seem to generate particles regularly, but don't increment the total.

I believe I've exported the local storage properly, and attached it to this issue.

[rks-ep-problem.txt](https://github.com/cwmonkey/reactor-knockoff/files/92934/rks-ep-problem.txt)

Thanks! It's been a lot of fun.

**Comment by cwmonkey** [comment]
Yeah this potential issue was always in the back of my mind. Before I dig into it, I am going to assume the EP you have is out of JavaScript's "safe integer" range and the number keeps getting rounded down to some floating point number.

If that's the case I'll see if using a big int library will fix the problems as well as not slow the game down too much.

Thanks for the report!

**Comment by egon010** [comment]
I only have a few thousand EPs

**Comment by cwmonkey** [comment]
Ah, I read the original message wrong. So the number isn't ticking up like in this gif?

http://i.imgur.com/IFf2KUl.gif

The first number will stay until you "reboot" the game in the experiments tab.

**Comment by egon010** [comment]
It is ticking up. The first number has never been anything other than 0 (and I haven't spent any), but it's possible I don't understand how it's supposed to work.

**Comment by cwmonkey** [comment]
You store up EP until you reboot (restart the game). Click "Experiments" on the top nav then click "Reboot for X Exotic Particles (EP)". After that you are able to buy special upgrades on the Experiments page.

Enjoy :)

**Comment by egon010** [comment]
Oh, well, then it's probably working as intended. I didn't understand how experiments worked. Let me play with it :-)

**Comment by cwmonkey** [comment]
Yeah, a lot of idle/incremental games have a "new game+" element. You restart the game from scratch and you have something that boosts your power in some way. In this case you get EP, which is a special currency you can use to buy powerful upgrades that last through resets.

I plan to add some features which explain this a little better.
