### ISSUE TITLE
Black Hole Particle Accelerator doesn't actively draws heat

### ISSUE THREAD

**Issue by asl97** [cwmonkey/reactor-knockoff#22]
Black Hole Particle Accelerator's description
> `Actively draws %transfer heat from the reactor at the cost of 1 power per 1 heat.`

It doesn't actually draws any heat from the reactor.

**Comment by cwmonkey** [comment]
Yeah I noticed that when I unhid the icon 😬 I put some code in place so it does _something_, but It'll still need some reworking.
