### ISSUE TITLE
Offline ticks might stall for an unreasonable amount of time

### ISSUE THREAD

**Issue by asl97** [cwmonkey/reactor-knockoff#23]
This is my fault, There should probably be some ui that shown the offline tick process and allow stopping processing if the player wanted.

**Comment by cwmonkey** [comment]
Ugh, yeah I wasn't sure what this was. I just made a commit to just reduce the tick time to 10ms for the duration of the offline ticks. I agree some sort of ui would be nicer but hopefully this will work as a temporary fix. Didn't realize how big of an issue this was until someone poked me about it 😬 

https://github.com/cwmonkey/reactor-knockoff/commit/a6b2c6818e556c3c58a5ab27187f05d7e43aa2b0
