### ISSUE TITLE
reflectors do not deteriorate

### ISSUE THREAD

**Issue by dasjester** [cwmonkey/reactor-knockoff#24]
i find that every type of reflector in the game does not lose any durability no matter how much time it is next to a component this makes certain upgrades useless and a waste of money i am unsure if this is a glitch or a bug but either way it's still manageable not having to replace reflectors

**Comment by SlavicMan** [comment]
![image](https://user-images.githubusercontent.com/53848716/91778408-81980e00-ec31-11ea-83e4-adf87afefebd.png)
same problem

**Comment by SlavicMan** [comment]
`	for ( let tile of game.active_tiles_2d ) {
		if ( tile.activated && tile.part ) {
			// Get the smallest amount of ticks where we can assume nothing will change.
			if ( tile.ticks !== 0 && tile.ticks < no_change_ticks ){
				no_change_ticks = tile.ticks;
			}
			let tile_part = tile.part;
			if ( tile_part.category === 'cell' ) {
				if ( tile.ticks !== 0 ) {
					power_add += tile.power;
					heat_add += tile.heat;
					tile.setTicks(tile.ticks - 1);

					if ( tile.reflectors.size ) {
						for ( let tile_reflector of tile.reflectors ) {
							tile_reflector.setTicks(tile_reflector.ticks - 1);

							// TODO: dedupe this and cell ticks
							if ( tile_reflector.ticks === 0 ) {
								if ( game.auto_buy_disabled !== true && tile_reflector.part.perpetual && game.current_money >= tile_reflector.part.cost ) {
									// auto replenish reflector
									game.current_money -= tile_reflector.part.cost;
									ui.say('var', 'current_money', game.current_money);
									tile_reflector.setTicks(tile_reflector.part.ticks);
								} else {
									tile_reflector.$el.classList.add('exploding');
									remove_part(tile_reflector, true);
								}
							}
						}
					}`


this is all I've found on reflector ticks in the source code

**Comment by SlavicMan** [comment]
![image](https://user-images.githubusercontent.com/53848716/91915308-5973e200-ecf9-11ea-83e7-b046e9aa39ff.png)

this is all I've found on reflector ticks

**Comment by SlavicMan** [comment]
![image](https://user-images.githubusercontent.com/53848716/92345845-14d9b380-f10a-11ea-8dcf-24a323ba68ae.png)
More on reflector pulses

**Comment by SlavicMan** [comment]
I fixed it
the update from 2018 bugged it out and I replaced the new game loop with the old one
