### ISSUE TITLE
UI issue on Firefox 87.0 x64

### ISSUE THREAD

**Issue by ScarletDetector** [cwmonkey/reactor-knockoff#28]
On the latest update of Firefox x64 (as of 2021-04-01), there's an issue about the UI in the _Options_.
When I press `Export save` or `Import save`, nothing seems to be happening afterwards at all, in fact _nothing happened at all_...

However, I tried with Chrome and everything still works as expected...

**Comment by asl97** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal

```
From version 53: this feature is behind thedom.dialog_element.enabled preferences (needs to be set to true). To change preferences in Firefox, visit about:config.
```

See bug [840640](https://bugzil.la/840640).

**Comment by ScarletDetector** [comment]
> 
> 
> https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal
> 
> ```
> From version 53: this feature is behind thedom.dialog_element.enabled preferences (needs to be set to true). To change preferences in Firefox, visit about:config.
> ```
> 
> See bug [840640](https://bugzil.la/840640).

Thanks! That worked!
